name: CI

on:
  push:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/python@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_BANDIT_CONFIG_FILE: pyproject.toml
          SPELL_CSPELL_CONFIG_FILE: .config/cspell.json
          DISABLE_LINTERS: JSON_PRETTIER
          REPOSITORY_CHECKOV_CONFIG_FILE: .config/.checkov.yml
      - name: Archive Production Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
